spring:
  application:
    name: payment

  datasource:
    url: jdbc:mysql://localhost:3306/payment_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8084

logging:
  file:
    name: logs/application.log

  logback:
    rollingpolicy:
      file-name-pattern: /inventory-service/logs/application.%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB
      max-history: 30

  level:
    root: INFO
    com.Ecom.inventory_service: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

product:
  service:
    url: "http://localhost:8081/api/product"

order:
  service:
    url: "http://localhost:8083/api/orders"